# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='location',
            field=models.CharField(choices=[('nakuru', 'nakuru'), ('nyeri', 'nyeri'), ('mombasa', 'mombasa')], max_length=80, null=True),
        ),
    ]
